# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class AttachinterfacescreatenetIdreqInterfaceAttachment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fixed_ips': 'list[FixedIp]',
        'net_id': 'str'
    }

    attribute_map = {
        'fixed_ips': 'fixed_ips',
        'net_id': 'net_id'
    }

    def __init__(self, fixed_ips=None, net_id=None, _configuration=None):  # noqa: E501
        """AttachinterfacescreatenetIdreqInterfaceAttachment - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._fixed_ips = None
        self._net_id = None
        self.discriminator = None

        if fixed_ips is not None:
            self.fixed_ips = fixed_ips
        if net_id is not None:
            self.net_id = net_id

    @property
    def fixed_ips(self):
        """Gets the fixed_ips of this AttachinterfacescreatenetIdreqInterfaceAttachment.  # noqa: E501


        :return: The fixed_ips of this AttachinterfacescreatenetIdreqInterfaceAttachment.  # noqa: E501
        :rtype: list[FixedIp]
        """
        return self._fixed_ips

    @fixed_ips.setter
    def fixed_ips(self, fixed_ips):
        """Sets the fixed_ips of this AttachinterfacescreatenetIdreqInterfaceAttachment.


        :param fixed_ips: The fixed_ips of this AttachinterfacescreatenetIdreqInterfaceAttachment.  # noqa: E501
        :type: list[FixedIp]
        """

        self._fixed_ips = fixed_ips

    @property
    def net_id(self):
        """Gets the net_id of this AttachinterfacescreatenetIdreqInterfaceAttachment.  # noqa: E501


        :return: The net_id of this AttachinterfacescreatenetIdreqInterfaceAttachment.  # noqa: E501
        :rtype: str
        """
        return self._net_id

    @net_id.setter
    def net_id(self, net_id):
        """Sets the net_id of this AttachinterfacescreatenetIdreqInterfaceAttachment.


        :param net_id: The net_id of this AttachinterfacescreatenetIdreqInterfaceAttachment.  # noqa: E501
        :type: str
        """

        self._net_id = net_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AttachinterfacescreatenetIdreqInterfaceAttachment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AttachinterfacescreatenetIdreqInterfaceAttachment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AttachinterfacescreatenetIdreqInterfaceAttachment):
            return True

        return self.to_dict() != other.to_dict()
