# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class FlavorAccessAddTenantReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'add_tenant_access': 'FlavoraccessaddtenantreqAddTenantAccess'
    }

    attribute_map = {
        'add_tenant_access': 'addTenantAccess'
    }

    def __init__(self, add_tenant_access=None, _configuration=None):  # noqa: E501
        """FlavorAccessAddTenantReq - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._add_tenant_access = None
        self.discriminator = None

        if add_tenant_access is not None:
            self.add_tenant_access = add_tenant_access

    @property
    def add_tenant_access(self):
        """Gets the add_tenant_access of this FlavorAccessAddTenantReq.  # noqa: E501


        :return: The add_tenant_access of this FlavorAccessAddTenantReq.  # noqa: E501
        :rtype: FlavoraccessaddtenantreqAddTenantAccess
        """
        return self._add_tenant_access

    @add_tenant_access.setter
    def add_tenant_access(self, add_tenant_access):
        """Sets the add_tenant_access of this FlavorAccessAddTenantReq.


        :param add_tenant_access: The add_tenant_access of this FlavorAccessAddTenantReq.  # noqa: E501
        :type: FlavoraccessaddtenantreqAddTenantAccess
        """

        self._add_tenant_access = add_tenant_access

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FlavorAccessAddTenantReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FlavorAccessAddTenantReq):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FlavorAccessAddTenantReq):
            return True

        return self.to_dict() != other.to_dict()
