# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class HostPutMaintenanceReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'maintenance_mode': 'str'
    }

    attribute_map = {
        'status': 'status',
        'maintenance_mode': 'maintenance_mode'
    }

    def __init__(self, status=None, maintenance_mode=None, _configuration=None):  # noqa: E501
        """HostPutMaintenanceReq - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._maintenance_mode = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if maintenance_mode is not None:
            self.maintenance_mode = maintenance_mode

    @property
    def status(self):
        """Gets the status of this HostPutMaintenanceReq.  # noqa: E501


        :return: The status of this HostPutMaintenanceReq.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this HostPutMaintenanceReq.


        :param status: The status of this HostPutMaintenanceReq.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def maintenance_mode(self):
        """Gets the maintenance_mode of this HostPutMaintenanceReq.  # noqa: E501


        :return: The maintenance_mode of this HostPutMaintenanceReq.  # noqa: E501
        :rtype: str
        """
        return self._maintenance_mode

    @maintenance_mode.setter
    def maintenance_mode(self, maintenance_mode):
        """Sets the maintenance_mode of this HostPutMaintenanceReq.


        :param maintenance_mode: The maintenance_mode of this HostPutMaintenanceReq.  # noqa: E501
        :type: str
        """

        self._maintenance_mode = maintenance_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HostPutMaintenanceReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostPutMaintenanceReq):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HostPutMaintenanceReq):
            return True

        return self.to_dict() != other.to_dict()
