# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class KeypairsimportpostreqKeypair(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'public_key': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'public_key': 'public_key',
        'user_id': 'user_id'
    }

    def __init__(self, name=None, type=None, public_key=None, user_id=None, _configuration=None):  # noqa: E501
        """KeypairsimportpostreqKeypair - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._type = None
        self._public_key = None
        self._user_id = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if public_key is not None:
            self.public_key = public_key
        if user_id is not None:
            self.user_id = user_id

    @property
    def name(self):
        """Gets the name of this KeypairsimportpostreqKeypair.  # noqa: E501


        :return: The name of this KeypairsimportpostreqKeypair.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this KeypairsimportpostreqKeypair.


        :param name: The name of this KeypairsimportpostreqKeypair.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this KeypairsimportpostreqKeypair.  # noqa: E501


        :return: The type of this KeypairsimportpostreqKeypair.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this KeypairsimportpostreqKeypair.


        :param type: The type of this KeypairsimportpostreqKeypair.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def public_key(self):
        """Gets the public_key of this KeypairsimportpostreqKeypair.  # noqa: E501


        :return: The public_key of this KeypairsimportpostreqKeypair.  # noqa: E501
        :rtype: str
        """
        return self._public_key

    @public_key.setter
    def public_key(self, public_key):
        """Sets the public_key of this KeypairsimportpostreqKeypair.


        :param public_key: The public_key of this KeypairsimportpostreqKeypair.  # noqa: E501
        :type: str
        """

        self._public_key = public_key

    @property
    def user_id(self):
        """Gets the user_id of this KeypairsimportpostreqKeypair.  # noqa: E501


        :return: The user_id of this KeypairsimportpostreqKeypair.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this KeypairsimportpostreqKeypair.


        :param user_id: The user_id of this KeypairsimportpostreqKeypair.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeypairsimportpostreqKeypair, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeypairsimportpostreqKeypair):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KeypairsimportpostreqKeypair):
            return True

        return self.to_dict() != other.to_dict()
