# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip_protocol': 'str',
        'from_port': 'str',
        'to_port': 'str',
        'cidr': 'str'
    }

    attribute_map = {
        'ip_protocol': 'ip_protocol',
        'from_port': 'from_port',
        'to_port': 'to_port',
        'cidr': 'cidr'
    }

    def __init__(self, ip_protocol=None, from_port=None, to_port=None, cidr=None, _configuration=None):  # noqa: E501
        """SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ip_protocol = None
        self._from_port = None
        self._to_port = None
        self._cidr = None
        self.discriminator = None

        if ip_protocol is not None:
            self.ip_protocol = ip_protocol
        if from_port is not None:
            self.from_port = from_port
        if to_port is not None:
            self.to_port = to_port
        if cidr is not None:
            self.cidr = cidr

    @property
    def ip_protocol(self):
        """Gets the ip_protocol of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501


        :return: The ip_protocol of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501
        :rtype: str
        """
        return self._ip_protocol

    @ip_protocol.setter
    def ip_protocol(self, ip_protocol):
        """Sets the ip_protocol of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.


        :param ip_protocol: The ip_protocol of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501
        :type: str
        """

        self._ip_protocol = ip_protocol

    @property
    def from_port(self):
        """Gets the from_port of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501


        :return: The from_port of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501
        :rtype: str
        """
        return self._from_port

    @from_port.setter
    def from_port(self, from_port):
        """Sets the from_port of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.


        :param from_port: The from_port of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501
        :type: str
        """

        self._from_port = from_port

    @property
    def to_port(self):
        """Gets the to_port of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501


        :return: The to_port of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501
        :rtype: str
        """
        return self._to_port

    @to_port.setter
    def to_port(self, to_port):
        """Sets the to_port of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.


        :param to_port: The to_port of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501
        :type: str
        """

        self._to_port = to_port

    @property
    def cidr(self):
        """Gets the cidr of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501


        :return: The cidr of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501
        :rtype: str
        """
        return self._cidr

    @cidr.setter
    def cidr(self, cidr):
        """Sets the cidr of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.


        :param cidr: The cidr of this SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule.  # noqa: E501
        :type: str
        """

        self._cidr = cidr

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SecuritygroupdefaultrulescreatereqSecurityGroupDefaultRule):
            return True

        return self.to_dict() != other.to_dict()
