# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.server_migrations_api import ServerMigrationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServerMigrationsApi(unittest.TestCase):
    """ServerMigrationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.server_migrations_api.ServerMigrationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_servers_server_id_migrations_get(self):
        """Test case for v21_servers_server_id_migrations_get

        """
        pass

    def test_v21_servers_server_id_migrations_migration_id_action_post(self):
        """Test case for v21_servers_server_id_migrations_migration_id_action_post

        """
        pass

    def test_v21_servers_server_id_migrations_migration_id_delete(self):
        """Test case for v21_servers_server_id_migrations_migration_id_delete

        """
        pass

    def test_v21_servers_server_id_migrations_migration_id_get(self):
        """Test case for v21_servers_server_id_migrations_migration_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
