# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_server_tags_api import OsServerTagsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsServerTagsApi(unittest.TestCase):
    """OsServerTagsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_server_tags_api.OsServerTagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_servers_server_id_tags_delete(self):
        """Test case for v21_servers_server_id_tags_delete

        """
        pass

    def test_v21_servers_server_id_tags_get(self):
        """Test case for v21_servers_server_id_tags_get

        """
        pass

    def test_v21_servers_server_id_tags_put(self):
        """Test case for v21_servers_server_id_tags_put

        """
        pass

    def test_v21_servers_server_id_tags_tag_delete(self):
        """Test case for v21_servers_server_id_tags_tag_delete

        """
        pass

    def test_v21_servers_server_id_tags_tag_get(self):
        """Test case for v21_servers_server_id_tags_tag_get

        """
        pass

    def test_v21_servers_server_id_tags_tag_put(self):
        """Test case for v21_servers_server_id_tags_tag_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
