# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_server_groups_api import OsServerGroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsServerGroupsApi(unittest.TestCase):
    """OsServerGroupsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_server_groups_api.OsServerGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_os_server_groups_get(self):
        """Test case for v21_os_server_groups_get

        """
        pass

    def test_v21_os_server_groups_post(self):
        """Test case for v21_os_server_groups_post

        """
        pass

    def test_v21_os_server_groups_server_group_id_delete(self):
        """Test case for v21_os_server_groups_server_group_id_delete

        """
        pass

    def test_v21_os_server_groups_server_group_id_get(self):
        """Test case for v21_os_server_groups_server_group_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
