# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_volume_attachments_api import OsVolumeAttachmentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsVolumeAttachmentsApi(unittest.TestCase):
    """OsVolumeAttachmentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_volume_attachments_api.OsVolumeAttachmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_servers_server_id_os_volume_attachments_get(self):
        """Test case for v21_servers_server_id_os_volume_attachments_get

        """
        pass

    def test_v21_servers_server_id_os_volume_attachments_post(self):
        """Test case for v21_servers_server_id_os_volume_attachments_post

        """
        pass

    def test_v21_servers_server_id_os_volume_attachments_volume_id_delete(self):
        """Test case for v21_servers_server_id_os_volume_attachments_volume_id_delete

        """
        pass

    def test_v21_servers_server_id_os_volume_attachments_volume_id_get(self):
        """Test case for v21_servers_server_id_os_volume_attachments_volume_id_get

        """
        pass

    def test_v21_servers_server_id_os_volume_attachments_volume_id_put(self):
        """Test case for v21_servers_server_id_os_volume_attachments_volume_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
