# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_volumes_api import OsVolumesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsVolumesApi(unittest.TestCase):
    """OsVolumesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_volumes_api.OsVolumesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_os_snapshots_detail_get(self):
        """Test case for v21_os_snapshots_detail_get

        """
        pass

    def test_v21_os_snapshots_get(self):
        """Test case for v21_os_snapshots_get

        """
        pass

    def test_v21_os_snapshots_post(self):
        """Test case for v21_os_snapshots_post

        """
        pass

    def test_v21_os_snapshots_snapshot_id_delete(self):
        """Test case for v21_os_snapshots_snapshot_id_delete

        """
        pass

    def test_v21_os_snapshots_snapshot_id_get(self):
        """Test case for v21_os_snapshots_snapshot_id_get

        """
        pass

    def test_v21_os_volumes_detail_get(self):
        """Test case for v21_os_volumes_detail_get

        """
        pass

    def test_v21_os_volumes_get(self):
        """Test case for v21_os_volumes_get

        """
        pass

    def test_v21_os_volumes_post(self):
        """Test case for v21_os_volumes_post

        """
        pass

    def test_v21_os_volumes_volume_id_delete(self):
        """Test case for v21_os_volumes_volume_id_delete

        """
        pass

    def test_v21_os_volumes_volume_id_get(self):
        """Test case for v21_os_volumes_volume_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
