# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_quota_class_sets_api import OsQuotaClassSetsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsQuotaClassSetsApi(unittest.TestCase):
    """OsQuotaClassSetsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_quota_class_sets_api.OsQuotaClassSetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_os_quota_class_sets_id_get(self):
        """Test case for v21_os_quota_class_sets_id_get

        """
        pass

    def test_v21_os_quota_class_sets_id_put(self):
        """Test case for v21_os_quota_class_sets_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
