# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_floating_ips_api import OsFloatingIpsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsFloatingIpsApi(unittest.TestCase):
    """OsFloatingIpsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_floating_ips_api.OsFloatingIpsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_os_floating_ips_floating_ip_id_delete(self):
        """Test case for v21_os_floating_ips_floating_ip_id_delete

        """
        pass

    def test_v21_os_floating_ips_floating_ip_id_get(self):
        """Test case for v21_os_floating_ips_floating_ip_id_get

        """
        pass

    def test_v21_os_floating_ips_get(self):
        """Test case for v21_os_floating_ips_get

        """
        pass

    def test_v21_os_floating_ips_post(self):
        """Test case for v21_os_floating_ips_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
