# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_floating_ip_pools_api import OsFloatingIpPoolsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsFloatingIpPoolsApi(unittest.TestCase):
    """OsFloatingIpPoolsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_floating_ip_pools_api.OsFloatingIpPoolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_os_floating_ip_pools_get(self):
        """Test case for v21_os_floating_ip_pools_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
