# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.updatevolumeattachmentdeleteflagreq_volume_attachment import UpdatevolumeattachmentdeleteflagreqVolumeAttachment  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdatevolumeattachmentdeleteflagreqVolumeAttachment(unittest.TestCase):
    """UpdatevolumeattachmentdeleteflagreqVolumeAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatevolumeattachmentdeleteflagreqVolumeAttachment(self):
        """Test UpdatevolumeattachmentdeleteflagreqVolumeAttachment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.updatevolumeattachmentdeleteflagreq_volume_attachment.UpdatevolumeattachmentdeleteflagreqVolumeAttachment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
