# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.server_topology_api import ServerTopologyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServerTopologyApi(unittest.TestCase):
    """ServerTopologyApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.server_topology_api.ServerTopologyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_servers_server_id_topology_get(self):
        """Test case for v21_servers_server_id_topology_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
