# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cach import Cach  # noqa: E501
from swagger_client.rest import ApiException


class TestCach(unittest.TestCase):
    """Cach unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCach(self):
        """Test Cach"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cach.Cach()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
