# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_virtual_interfaces_api import OsVirtualInterfacesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsVirtualInterfacesApi(unittest.TestCase):
    """OsVirtualInterfacesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_virtual_interfaces_api.OsVirtualInterfacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_servers_server_id_os_virtual_interfaces_get(self):
        """Test case for v21_servers_server_id_os_virtual_interfaces_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
