# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.versions_api import VersionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVersionsApi(unittest.TestCase):
    """VersionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.versions_api.VersionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_api_version_get(self):
        """Test case for v21_api_version_get

        """
        pass

    def test_v21_get(self):
        """Test case for v21_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
