# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.os_baremetal_nodes_api import OsBaremetalNodesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOsBaremetalNodesApi(unittest.TestCase):
    """OsBaremetalNodesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.os_baremetal_nodes_api.OsBaremetalNodesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_os_baremetal_nodes_get(self):
        """Test case for v21_os_baremetal_nodes_get

        """
        pass

    def test_v21_os_baremetal_nodes_node_id_get(self):
        """Test case for v21_os_baremetal_nodes_node_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
