# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.extensions_api import ExtensionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExtensionsApi(unittest.TestCase):
    """ExtensionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.extensions_api.ExtensionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_extensions_alias_get(self):
        """Test case for v21_extensions_alias_get

        """
        pass

    def test_v21_extensions_get(self):
        """Test case for v21_extensions_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
