# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.aggregate_add_host_post_req import AggregateAddHostPostReq  # noqa: E501
from swagger_client.rest import ApiException


class TestAggregateAddHostPostReq(unittest.TestCase):
    """AggregateAddHostPostReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregateAddHostPostReq(self):
        """Test AggregateAddHostPostReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.aggregate_add_host_post_req.AggregateAddHostPostReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
