# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.flavors_api import FlavorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFlavorsApi(unittest.TestCase):
    """FlavorsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.flavors_api.FlavorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v21_flavors_detail_get(self):
        """Test case for v21_flavors_detail_get

        """
        pass

    def test_v21_flavors_flavor_id_delete(self):
        """Test case for v21_flavors_flavor_id_delete

        """
        pass

    def test_v21_flavors_flavor_id_get(self):
        """Test case for v21_flavors_flavor_id_get

        """
        pass

    def test_v21_flavors_flavor_id_put(self):
        """Test case for v21_flavors_flavor_id_put

        """
        pass

    def test_v21_flavors_get(self):
        """Test case for v21_flavors_get

        """
        pass

    def test_v21_flavors_post(self):
        """Test case for v21_flavors_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
