# coding: utf-8

"""
    Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class OsInterfaceApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def v21_servers_server_id_os_interface_get(self, server_id, **kwargs):  # noqa: E501
        """v21_servers_server_id_os_interface_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v21_servers_server_id_os_interface_get(server_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str server_id: The UUID of the server.  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v21_servers_server_id_os_interface_get_with_http_info(server_id, **kwargs)  # noqa: E501
        else:
            (data) = self.v21_servers_server_id_os_interface_get_with_http_info(server_id, **kwargs)  # noqa: E501
            return data

    def v21_servers_server_id_os_interface_get_with_http_info(self, server_id, **kwargs):  # noqa: E501
        """v21_servers_server_id_os_interface_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v21_servers_server_id_os_interface_get_with_http_info(server_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str server_id: The UUID of the server.  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['server_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v21_servers_server_id_os_interface_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'server_id' is set
        if self.api_client.client_side_validation and ('server_id' not in params or
                                                       params['server_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `server_id` when calling `v21_servers_server_id_os_interface_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['server_id'] = params['server_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v2.1/servers/{server_id}/os-interface', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v21_servers_server_id_os_interface_port_id_delete(self, server_id, port_id, **kwargs):  # noqa: E501
        """v21_servers_server_id_os_interface_port_id_delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v21_servers_server_id_os_interface_port_id_delete(server_id, port_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str server_id: The UUID of the server.  (required)
        :param str port_id: The UUID of the port.  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v21_servers_server_id_os_interface_port_id_delete_with_http_info(server_id, port_id, **kwargs)  # noqa: E501
        else:
            (data) = self.v21_servers_server_id_os_interface_port_id_delete_with_http_info(server_id, port_id, **kwargs)  # noqa: E501
            return data

    def v21_servers_server_id_os_interface_port_id_delete_with_http_info(self, server_id, port_id, **kwargs):  # noqa: E501
        """v21_servers_server_id_os_interface_port_id_delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v21_servers_server_id_os_interface_port_id_delete_with_http_info(server_id, port_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str server_id: The UUID of the server.  (required)
        :param str port_id: The UUID of the port.  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['server_id', 'port_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v21_servers_server_id_os_interface_port_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'server_id' is set
        if self.api_client.client_side_validation and ('server_id' not in params or
                                                       params['server_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `server_id` when calling `v21_servers_server_id_os_interface_port_id_delete`")  # noqa: E501
        # verify the required parameter 'port_id' is set
        if self.api_client.client_side_validation and ('port_id' not in params or
                                                       params['port_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `port_id` when calling `v21_servers_server_id_os_interface_port_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['server_id'] = params['server_id']  # noqa: E501
        if 'port_id' in params:
            path_params['port_id'] = params['port_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v2.1/servers/{server_id}/os-interface/{port_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v21_servers_server_id_os_interface_port_id_get(self, server_id, port_id, **kwargs):  # noqa: E501
        """v21_servers_server_id_os_interface_port_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v21_servers_server_id_os_interface_port_id_get(server_id, port_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str server_id: The UUID of the server.  (required)
        :param str port_id: The UUID of the port.  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v21_servers_server_id_os_interface_port_id_get_with_http_info(server_id, port_id, **kwargs)  # noqa: E501
        else:
            (data) = self.v21_servers_server_id_os_interface_port_id_get_with_http_info(server_id, port_id, **kwargs)  # noqa: E501
            return data

    def v21_servers_server_id_os_interface_port_id_get_with_http_info(self, server_id, port_id, **kwargs):  # noqa: E501
        """v21_servers_server_id_os_interface_port_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v21_servers_server_id_os_interface_port_id_get_with_http_info(server_id, port_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str server_id: The UUID of the server.  (required)
        :param str port_id: The UUID of the port.  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['server_id', 'port_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v21_servers_server_id_os_interface_port_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'server_id' is set
        if self.api_client.client_side_validation and ('server_id' not in params or
                                                       params['server_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `server_id` when calling `v21_servers_server_id_os_interface_port_id_get`")  # noqa: E501
        # verify the required parameter 'port_id' is set
        if self.api_client.client_side_validation and ('port_id' not in params or
                                                       params['port_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `port_id` when calling `v21_servers_server_id_os_interface_port_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['server_id'] = params['server_id']  # noqa: E501
        if 'port_id' in params:
            path_params['port_id'] = params['port_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v2.1/servers/{server_id}/os-interface/{port_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v21_servers_server_id_os_interface_post(self, server_id, attach_interfaces_create_net_id_req, **kwargs):  # noqa: E501
        """v21_servers_server_id_os_interface_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v21_servers_server_id_os_interface_post(server_id, attach_interfaces_create_net_id_req, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str server_id: The UUID of the server.  (required)
        :param AttachInterfacesCreateNetIdReq attach_interfaces_create_net_id_req: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v21_servers_server_id_os_interface_post_with_http_info(server_id, attach_interfaces_create_net_id_req, **kwargs)  # noqa: E501
        else:
            (data) = self.v21_servers_server_id_os_interface_post_with_http_info(server_id, attach_interfaces_create_net_id_req, **kwargs)  # noqa: E501
            return data

    def v21_servers_server_id_os_interface_post_with_http_info(self, server_id, attach_interfaces_create_net_id_req, **kwargs):  # noqa: E501
        """v21_servers_server_id_os_interface_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v21_servers_server_id_os_interface_post_with_http_info(server_id, attach_interfaces_create_net_id_req, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str server_id: The UUID of the server.  (required)
        :param AttachInterfacesCreateNetIdReq attach_interfaces_create_net_id_req: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['server_id', 'attach_interfaces_create_net_id_req']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v21_servers_server_id_os_interface_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'server_id' is set
        if self.api_client.client_side_validation and ('server_id' not in params or
                                                       params['server_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `server_id` when calling `v21_servers_server_id_os_interface_post`")  # noqa: E501
        # verify the required parameter 'attach_interfaces_create_net_id_req' is set
        if self.api_client.client_side_validation and ('attach_interfaces_create_net_id_req' not in params or
                                                       params['attach_interfaces_create_net_id_req'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `attach_interfaces_create_net_id_req` when calling `v21_servers_server_id_os_interface_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['server_id'] = params['server_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'attach_interfaces_create_net_id_req' in params:
            body_params = params['attach_interfaces_create_net_id_req']
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v2.1/servers/{server_id}/os-interface', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
